# .github/workflows/unittests.yml

name: Run Unit Tests

on:
  push:
    branches: [main, task1]  # Run tests on pushes to these branches
  pull_request:
    branches: [main, task1]  # Run tests on PRs targeting these branches

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        pytest  # Replace with your test runner if different
